apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: 1router-frontend
  namespace: 1router
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - 1router.com
    secretName: 1router-tls
  rules:
  - host: 1router.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: 1router-frontend
            port:
              number: 80
